### ISSUE TITLE
Remove documentation related to hashed unique heading anchors

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1199]
Hugo generates _hashed_ unique heading anchors under the following conditions:

```toml
[markup]
defaultMarkdownHandler = "blackfriday"  # Default is goldmark
[markup.blackFriday]
plainIDAnchors = false                  # Default is true
```

Neither of these are the default settings, and Blackfriday is slated for deprecation (https://github.com/gohugoio/hugo/issues/6487). 

The current documentation suggests that the default behavior is to generate _hashed_ unique heading anchors. It is not. By default, we generate unique identifiers on a _page_ by incrementing with an integer.

See <https://gohugo.io/content-management/cross-references/#hugo-heading-anchors>

PR to follow...
