### ISSUE TITLE
Add markdownlint GitHub Action

### ISSUE THREAD

**Issue by tohn** [gohugoio/hugoDocs#1604]
As suggested in https://github.com/gohugoio/hugoDocs/pull/1597#issuecomment-988996041, here is a simple draft for this action (`.github/workflows/markdownlint.yml`):

```yml
---
name: markdownlint
on: pull_request  # yamllint disable-line rule:truthy
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Run markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          config_file: .markdownlint.yaml
          files: .
```

This will fail at the moment though :wink:

**Comment by coliff** [comment]
thanks for this. It's unfortunate that that particular GitHub Action doesn't have much in the way of configuration. Ideally I think linting would only occur on changed files - so maybe using GitHub's Super Linter could be a better option.

```yml
name: Lint Code Base

# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
