### ISSUE TITLE
`.Lastmod` does not behave as documented

### ISSUE THREAD

**Issue by dadoonet** [gohugoio/hugoDocs#1624]
As reported at https://discourse.gohugo.io/t/gitinfo-authordate-overriding-lastmod-frontmatter-in-lastmod-variable/11114/2 and after a discussion in https://github.com/gohugoio/hugo/issues/5523#issuecomment-1011260798, I think that the documentation is not consistent with the current behavior.

I'd prefer that we change the behavior as the documentation looks what I'm actually expected.

Here is what [the documentation](https://gohugo.io/variables/page/) says about `.Lastmod`:

> the date the content was last modified. `.Lastmod` pulls from the `lastmod` field in a content’s front matter.
> * If `lastmod` is not set, and `.GitInfo` feature is disabled, the front matter `date` field will be used.
> * If `lastmod` is not set, and `.GitInfo` feature is enabled, `.GitInfo.AuthorDate` will be used instead.

The current behavior is that when `.GitInfo` feature is enabled, it automatically uses `.GitInfo.AuthorDate` as the value for `.Lastmod` even if we try to force it using `lastmod` (so `lastmod` is totally ignored in that case).

The conclusion of the discussion in the forum was:

> The current documentation looks a little inaccurate in this area, but there is a way around it:

So we need to modify the documentation accordingly or better IMHO change the behavior to be as expected.
To change the behavior, we need to change the default order.

From:

```yml
frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date
```

To:

```yml
frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate
  publishDate:
  - publishDate
  - date
```
