### ISSUE TITLE
Document `urlquery` function

### ISSUE THREAD

**Issue by schnerring** [gohugoio/hugoDocs#1627]
Consider the following example:

```html
{{ $formatString := "https://www.facebook.com/sharer.php?u={url}" }}
{{ $result := replace $formatString "{url}" .Permalink }}
```

The issue I've had is that I want to "percent-encode" `.Permalink`. People have had this issue before:

* https://discourse.gohugo.io/t/urlencode-in-hugo/24215
* https://discourse.gohugo.io/t/is-there-a-url-encoder-function-in-hugo/2239/8

I've poked around the Hugo code base and found an undocumented built-in Hugo function `urlquery`:

https://github.com/gohugoio/hugo/blob/3d5dbdcb1a11b059fc2f93ed6fadb9009bf72673/tpl/internal/go_templates/texttemplate/funcs.go#L51

https://github.com/gohugoio/hugo/blob/3d5dbdcb1a11b059fc2f93ed6fadb9009bf72673/tpl/internal/go_templates/texttemplate/funcs.go#L738-L742

It's a thin wrapper around `url.QueryEscape` and perfectly solves my issue:

```html
{{ urlquery .Permalink }}
```

Is the function here to stay and just misses documentation?

**Comment by jmooring** [comment]
@schnerring Thanks for this; much appreciated. Note that your example can be addressed with the [querify](https://gohugo.io/functions/querify) function.

```
{{ printf "%s?%s" "https://www.facebook.com/sharer.php" (querify "u" .Permalink) }}
```

**Comment by schnerring** [comment]
I understand that, but my _actual_ requirement is a bit more complex.

[Here is the partial I use as "social provider"](https://github.com/schnerring/hugo-theme-gruvbox/blob/main/layouts/partials/social-share.html):

```html
{{ $url := .Permalink }}
{{ $title := .Title }}
{{ with $.Site.Params.socialShare }}
  <div class="social-share">
    <strong>Share this post: </strong>
    {{ range . }}
      {{ $href := .formatString }}
      {{ $href := replace $href "{url}" (urlquery $url) }}
      {{ $href := replace $href "{title}" (urlquery $title) }}
      <a href="{{ $href | safeURL }}" target="_blank" rel="noreferrer">
        {{ if eq .icon "Mail" }}
          {{ partial "icons/tabler-icon.html" .icon }}
        {{ else }}
          {{ partial "icons/simple-icon.html" .icon }}
        {{ end }}
      </a>
    {{ end }}
  </div>
{{ end }}
```

This allows me to add social share buttons via Hugo config like this

```toml
[[params.socialShare]]
    icon = "Facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    icon = "Reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    icon = "Twitter"
    formatString = "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    icon = "LinkedIn"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    icon = "WhatsApp"
    formatString = "whatsapp://send/?text={title}%20{url}"
  [[params.socialShare]]
    icon = "Tumblr"
    formatString = "https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={title}"
```
