### ISSUE TITLE
Document minify's HTML templateDelims configuration option

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#2346]
See https://github.com/tdewolff/minify/commit/24bb939069496d63166652f528033bd3f792fb89

```yaml
minify:
  tdewolff:
    html:
      keepComments: false
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: false
      keepWhitespace: false
      templateDelims:
      - ""
      - ""
```
