### ISSUE TITLE
data/docs.yaml duplicates extension in output.layouts.Example ?

### ISSUE THREAD

**Issue by irkode** [gohugoio/hugoDocs#2423]
I just had a look on [https://gohugo.io/templates/lookup-order/](https://gohugo.io/templates/lookup-order/) while experimenting with Hugo.

Tthe lookup order tables there have some extensions duplicated.

### Example : [Home Page Table](http://127.0.0.1:1313/templates/lookup-order/#home-page)

| Example	|OutputFormat|Suffix|Template Lookup Order|
|-|-|-|-|
|Home page|	html	| html	| 1. layouts/index.html |
|||| 2. layouts/home.**html.html** |
|||| 3. layouts/list.**html.html** |
|||| 4 .layouts/index.html |

thought it is a bug in rendering and dived in - a good lerning session  - datatable-filtered shortcode. But it was not the shortcode.
the entries came directly from `/data/docs.yaml`.

### Example : [data/docs.yaml](https://github.com/gohugoio/hugoDocs/blob/master/data/docs.yaml)
```yaml
  - Example: Home page
    Kind: home
    OutputFormat: html
    Suffix: html
    Template Lookup Order:
    - layouts/index.html
    - layouts/home.html.html
    - layouts/list.html.html
    - layouts/index.html
```

I don't know if 

1. it's really the lookup setting
2. the docs.yaml has to duplicate some extensions for a reason somewhere else than in the visited page
3. it's is a bug.

My estimated guess would be it's a bug in the generation of the yaml file ;-)
last commit message for `/data/docs.yaml` mentions "Regen dochelper", so I guess there's something behind

There are 137 duplications in total
* 6 for json.json
* 131 for html.html
