### ISSUE TITLE
Mathematics in markdown, passthrough extension: improper yaml config

### ISSUE THREAD

**Issue by deining** [gohugoio/hugoDocs#2429]
While following the instructions given in the new section [Mathematics in markdown](https://gohugo.io/content-management/mathematics/), I ran into trouble:

According to [Step 1](https://gohugo.io/content-management/mathematics/#step-1) you should add this to your `hugo.yaml`:

```
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
params:
  math: true
```

This didn't work for me however. To make it work, I had to put line `enable: true` directly below the line `passthrough:`:

```
markup:
  goldmark:
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)

params:
  math: true
```
With that config, passthrough worked for me.
