### ISSUE TITLE
Quick Start: jarring textarea resize

### ISSUE THREAD

**Issue by jsprow** [gohugoio/hugoDocs#275]
I hope this isn't too nitpicky, but I noticed that, when you hover over the border on the code textareas (not actually textareas, I know), it has a little freakout.

![dec-13-2017 17-44-59](https://user-images.githubusercontent.com/15620432/33966676-754dc82c-e02e-11e7-911b-310071251c9e.gif)

I dug into it, and it looks like you've got some css handling the hover, where you adjust 'margin-right'. I suggest adding a transition for a less seizure-inducing experience. Something like:
```css
@media screen and (min-width: 60em) {
    pre.expand {
        margin-right: 0;
        transition: margin-right 200ms;
    }
    .full-width,pre.expand:hover {
        margin-right:-30vw;
        max-width: 100vw;
        transition: margin-right 200ms;
    }
}
```
![dec-13-2017 17-57-03](https://user-images.githubusercontent.com/15620432/33966870-267d101c-e02f-11e7-8f72-b3004f8dd5d5.gif)
Better?

I would have submitted a pull request, but I couldn't find the relevant file(s).

Thanks for all your hard work!
