### ISSUE TITLE
search: Glossary page does not appear in search results

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#3108]
This happens because the glossary has page kind "section" and our search config only looks for kind "page":

```text
selectorsToMatch: [".kind-page"],
```

We could hardcode something in the search config, but I'd rather do something extensible like using a front matter field:

site config:

```toml
[[cascade]]
  [cascade.params]
    searchable = true
  [cascade.target]
    kind = 'page'
[[cascade]]
  [cascade.params]
    searchable = false
  [cascade.target]
    kind = '{home,section,taxonomy,term}'
```

If `.Page.Params.searchable` is `true` we include `searchable` in the body element's `class` attribute.

And this way we can override the default behavior in front matter.
