### ISSUE TITLE
Change highlight style

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#425]
I noticed this when testing out the new (great) Go template Chroma lexer.

The current code style we use looks a little ... anonymous.

I propose we pick a little bolder choice.

For alternatives:
https://help.farbox.com/pygments.html

Note that to preview this in the docs you need to set

```toml
pygmentsUseClasses = false

# Then you can set
pygmentsStyle = "friendly"

# etc.
```

Current (friendly):

![image](https://user-images.githubusercontent.com/394382/37583990-fe6a248c-2b53-11e8-99fc-18e027ebcf69.png)

manni:

![image](https://user-images.githubusercontent.com/394382/37584057-35d8ddb4-2b54-11e8-8d44-8d46e3362eee.png)

trac:

![image](https://user-images.githubusercontent.com/394382/37584097-652f3626-2b54-11e8-9e01-ba69318c84fb.png)

Many pretty ...
